spring: 
    profiles: 
        active:
           - dev
---
spring:
    profiles: dev
    application:
        name: springcloud-config-hzit-dev
---
spring:
    profiles: test
    applicationsdfafdfd:
        name: springcloud-config-hzit-testsfsdfsfdfasdf
